\chyph
\def\fontprefix{cs}
\input texinfo
@comment %**start of header
@setfilename speechd-el.cs.info
@documentlanguage cs
@documentencoding ISO-8859-2
@set VERSION 1.0
@settitle speechd-el @value{VERSION}
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex vr cp
@comment %**end of header
@copying
Èeský pøeklad manuálu programu speechd-el, @value{VERSION}.

Copyright @copyright{} 2003, 2004 Brailcom, o.p.s.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts and no Back-Cover Texts.
A copy of the license is included in the section entitled ``GNU Free
Documentation License.''
@end quotation

You can also (at your option) distribute this manual under the GNU
General Public License:

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

A copy of the license is included in the section entitled ``GNU
General Public License''.
@end quotation
@end copying

@dircategory Sound
@dircategory Emacs
@direntry
* speechd-el cs: (speechd-el.cs).  Emacsové rozhraní ke Speech Dispatcher.
@end direntry

@titlepage
@title speechd-el
@subtitle pro verzi @value{VERSION}
@author Milan Zamazal
@author Brailcom, o.p.s.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top, Úvodem, (dir), (dir)
@top speechd-el

@insertcopying
@end ifnottex

@menu
* Úvodem::                      K@tie{}èemu je speechd-el a tento manuál?
* U¾ivatelská pøíruèka::        Pou¾ívání øeèového výstupu Emacsu.
* Elispová knihovna::           Pou¾ívání speechd-el v elispových programech.
* Kontaktní informace::         Oznamování chyb atd.

* Kopírování tohoto manuálu::   GNU Free Documentation License.
* Index::                       V¹eobjímající index.
@end menu

@c ****************************************************************************

@node Úvodem, U¾ivatelská pøíruèka, Top, Top
@chapter Úvodem
@cindex Speech Dispatcher

speechd-el je emacsový klient ke Speech Dispatcher.  Poskytuje
následující funkce:

@itemize @bullet
@item
@cindex SSIP
Elispovou knihovnu pro pøístup ke Speech Dispatcher s@tie{}vyu¾itím
soketové komunikace zalo¾ené na jeho komunikaèním protokolu (SSIP).

@item
Podporu pro øeèový výstup Emacsu, zamìøený zejména na prostøedky
potøebné pro vyu¾ívání Emacsu slepými a tì¾ce zrakovì posti¾enými
u¾ivateli.
@end itemize

Klíèové rysy speechd-el jsou:
@cindex rysy

@itemize @bullet
@item
Podporu pro automatické mluvení, bez nutnosti úprav ka¾dé emacsové
funkce, kterou je potøeba rozmluvit.  Vìt¹ina emacsových programù
z@tie{}distribuce Emacsu i@tie{}mimo ni získává øeèový výstup okam¾itì, bez
jakékoliv speciální podpory.

@item
Nejsou provádìny témìø ¾ádné zmìny standardního chování Emacsu a
nedochází ke konfliktùm s@tie{}u¾ivatelskými nastaveními.

@item
Plná spolupráce se Speech Dispatcher.

@item
Malý rozsah kódu.
@end itemize

Manuál popisuje øeèové u¾ivatelské rozhraní, jak si toto rozhraní
pøizpùsobit a roz¹íøit a elispovou knihovnu.  Doporuèujeme, aby
u¾ivatel byl èásteènì obeznámen se Speech Dispatcher na u¾ivatelské
úrovni, ale není to nezbytné.

@c ****************************************************************************

@node U¾ivatelská pøíruèka, Elispová knihovna, Úvodem, Top
@chapter U¾ivatelská pøíruèka speechd-el

speechd-el umo¾òuje pou¾ívat Emacs bez zobrazení na monitoru, pouze
jen s@tie{}øeèovým výstupem.  Hlavní oblast vyu¾ití je mezi slepci a
zrakovì posti¾enými lidmi, nicménì øeèový výstup mù¾e být u¾iteèný
i@tie{}pro celou øadu dal¹ích vìcí, podle toho co kdo potøebuje.

Nejnovìj¹í verzi speechd-el si mù¾ete stáhnout na
@url{http://www.freebsoft.org/pub/projects/speechd-el/}.

speechd-el pou¾ívá pro øeèový výstup Speech Dispatcher, tak¾e abyste
vùbec nìjaký øeèový výstup sly¹eli, potøebujete mít funkèní instalaci
Speech Dispatcher.  V¹echny informace o@tie{}Speech Dispatcher naleznete na
@url{http://www.freebsoft.org/speechd}.

@menu
* Instalace::                   Jak speechd-el nainstalovat.
* Spu¹tìní øeèového výstupu::   Jak jej rozmluvit.
* Pøíkazy::                     Jak jej pou¾ívat.
* Konfigurace::                 Základní konfigurace.
* Pokroèilá konfigurace::       Psaní vlastních reakcí na pøíkazy.
* Potí¾e::                      Kdy¾ se speechd-el chová podivnì.
* Tipy::                        U¾iteèné emacsové tipy.
* Oznamování chyb::             Chyby speechd-el a Speech Dispatcher.
@end menu

@node Instalace, Spu¹tìní øeèového výstupu, U¾ivatelská pøíruèka, U¾ivatelská pøíruèka
@section Instalace

speechd-el se nainstaluje následujícími kroky:

@enumerate
@item
Zkopírujte v¹echny @file{*.el} soubory z@tie{}distribuèního balíku nìkam do
emacsových adresáøù obsa¾ených v@tie{}cestì va¹eho Emacsu.

@item
Chcete-li, mù¾ete si @file{*.el} soubory zkompilovat.  To
doporuèujeme, proto¾e speechd-el bì¾í se zkompilovanými soubory
podstatnì rychleji.  Kompilaci mù¾ete provést pøíkazem

@example
make compile
@end example

Poté pøiinstalujte zkompilované soubory do emacsové cesty ke zdrojovým
souborùm speechd-el.

@item
Nainstalujte soubor @file{speechd-log-extractor} do nìkteré
z@tie{}cest obsa¾ených v@tie{}shellové promìnné PATH, napøíklad
do adresáøe @file{/usr/local/bin/}.

@item
Do svého @file{~/.emacs} si pøidejte následující øádek:

@lisp
(autoload 'speechd-speak "speechd-speak" nil t)
@end lisp
@end enumerate

Pro úspì¹ný provoz speechd-el je nutno mít nainstalované a spu¹tìné
Speech Dispatcher.  Doporuèená je verze@tie{}0.5 nebo vy¹¹í.

@node Spu¹tìní øeèového výstupu, Pøíkazy, Instalace, U¾ivatelská pøíruèka
@section Spu¹tìní øeèového výstupu

Po instalaci @file{*.el} souborù a restartu Emacsu mù¾ete
inicializovat øeèový výstup prostøednictvím pøíkazu @kbd{M-x
speechd-speak}.  Chcete-li, aby se tak dìlo automaticky pøi ka¾dém
startu Emacsu, pøidejte si do svého @file{~/.emacs} následující
øádek, za døíve vlo¾ený øádek s@tie{}@code{autoload}:

@lisp
(speechd-speak)
@end lisp

@table @kbd
@item M-x speechd-speak
@findex speechd-speak
@kindex C-e C-s
Inicializuj Emacs pro øeèový výstup a zaèni mluvit.

Prosím nezapomeòte, ¾e abyste nìco sly¹eli, musíte mít korektnì
nainstalováno Speech Dispatcher!

Po poèáteèním nastavení mù¾e být tento pøíkaz pou¾it znovu, v@tie{}pøípadì
potøeby restartu øeèové podpory.  Zejména jej musíte spustit poka¾dé,
kdy¾ je restartováno Speech Dispatcher.

Je-li pøíkaz zavolán s@tie{}prefixovým argumentem, jsou pøed jeho
provedením nejprve uzavøena v¹echna spojení na Speech Dispatcher.  To
je u¾iteèné v@tie{}pøípadì, kdy potøebujete zresetovat parametry v¹ech
spojení, viz @ref{Hlasy spojení}.

Po svém prvním zavolání se pøíkaz stane dostupným pod klávesou
@kbd{C-e C-s}.
@end table

@cindex vedlej¹í módy
Poté, co jsou provedena úvodní nastavení, je zapínání a vypínání
øeèového výstupu øízeno vedlej¹ími módy speechd-speak a
global-speechd-speak.  Pøíkazy pro pøepínání módù obvykle nejsou
pou¾ívány pøímo, mù¾ete místo nich pou¾ívat pøíkaz
@code{speechd-speak-toggle-speaking} (@pxref{Øídící pøíkazy}), ale
pokud je potøebujete, jsou k@tie{}dispozici.

@table @kbd
@item M-x speechd-speak-mode
@findex speechd-speak-mode
Zapni nebo vypni mluvení v@tie{}aktuálním bufferu.  Je-li pøíkaz zavolán
bez prefixového argumentu, pøepne mluvící mód.  Nenulový prefixový
argument zapne mluvení, nulový prefixový argument jej vypne.

@item M-x global-speechd-speak-mode
@findex global-speechd-speak-mode
Zapni nebo vypni mluvení globálnì.  Je-li pøíkaz zavolán
bez prefixového argumentu, pøepne mluvící mód.  S@tie{}prefixovým
argumentem zapne mluvení právì v@tie{}pøípadì, kdy je tento argument kladný.
@end table

@node Pøíkazy, Konfigurace, Spu¹tìní øeèového výstupu, U¾ivatelská pøíruèka
@section Pøíkazy

V¹echny základní pøíkazy speechd-el jsou dostupné pod spoleènou
prefixovou klávesou, kterou je implicitnì @kbd{C-e} (tuto prefixovou
klávesu lze zmìnit, @pxref{Konfigurace}).  Jestli¾e je prefixová
klávesa v@tie{}konfliktu s@tie{}nìkterým globálním pøíkazem Emacsu, pùvodní
pøíkaz je dostupný dvojím stiskem prefixové klávesy.  Napøíklad
v@tie{}pøípadì implicitního prefixu lze pøíkaz @code{end-of-line}, normálnì
dostupný pod klávesou @kbd{C-e}, vyvolat klávesovou kombinací @kbd{C-e
C-e}.

@menu
* Pøíkazy pro ètení::             Ètení èástí textu.
* Informující pøíkazy::           Informace o bufferu, módech, apod.
* Øídící pøíkazy::                Pøeru¹ení, nastavení rychlosti, apod.
* Pøíkazy nastavující parametry:: Modifikace øeèového výstupu.
* Hláskování::                    Jak hláskovat urèitý text.
* Ostatní pøíkazy::               Pomocné pøíkazy.
@end menu

@node Pøíkazy pro ètení, Informující pøíkazy, Pøíkazy, Pøíkazy
@subsection Pøíkazy pro ètení

@table @kbd
@item C-e l
@kindex C-e l
@findex speechd-speak-read-line
Pøeèti aktuální øádek (@code{speechd-speak-read-line}).
S@tie{}prefixovým argumentem pøeèti øádek jen od aktuální pozice
kurzoru do konce øádku.

@item C-e b
@kindex C-e b
@findex speechd-speak-read-buffer
Pøeèti aktuální buffer (@code{speechd-speak-read-buffer}).

@item C-e >
@kindex C-e >
@findex speechd-speak-read-rest-of-buffer
Pøeèti aktuální buffer od pozice kurzoru do konce bufferu
(@code{speechd-speak-read-rest-of-buffer}).

@item C-e o
@kindex C-e o
@findex speechd-speak-read-other-window
Pøeèti buffer v@tie{}jiném oknì, je-li nìjaké jiné okno otevøené
(@code{speechd-speak-read-other-window}).

@item C-e r
@kindex C-e r
@findex speechd-speak-read-region
Pøeèti aktuální oblast (@code{speechd-speak-read-region}).

@item C-e C-r
@kindex C-e C-r
@findex speechd-speak-read-rectangle
Pøeèti text v@tie{}obdélníkové oblasti (@code{speechd-speak-read-rectangle}).

@item C-e w
@kindex C-e w
@findex speechd-speak-read-word
Pøeèti nejbli¾¹í slovo za kurzorem (@code{speechd-speak-read-word}).

@item C-e .
@kindex C-e .
@findex speechd-speak-read-sentence
Pøeèti aktuální vìtu (@code{speechd-speak-read-sentence}).

@item C-e @{
@kindex C-e @{
@findex speechd-speak-read-paragraph
Pøeèti nejbli¾¹í odstavec za kurzorem (@code{speechd-speak-read-paragraph}).

@item C-e [
@kindex C-e [
@findex speechd-speak-read-page
Pøeèti nejbli¾¹í stránku za kurzorem (@code{speechd-speak-read-page}).

@item C-e '
@kindex C-e '
@findex speechd-speak-read-sexp
Pøeèti nejbli¾¹í symbolický výraz za kurzorem
(@code{speechd-speak-read-sexp}).

@item C-e c
@kindex C-e c
@findex speechd-speak-read-char
Pøeèti znak na pozici kurzoru (@code{speechd-speak-read-char}).

@item C-e C-n
@kindex C-e C-n
@findex speechd-speak-read-next-line
Pøeèti následující øádek (@code{speechd-speak-read-next-line}).

@item C-e C-p
@kindex C-e C-p
@findex speechd-speak-read-previous-line
Pøeèti pøedchozí øádek (@code{speechd-speak-read-previous-line}).

@item C-e m
@kindex C-e m
@findex speechd-speak-last-message
Pøeèti poslední zobrazené hlá¹ení Emacsu (@code{speechd-speak-last-message}).

@item C-e RET
@cindex mode line
@kindex C-e RET
@findex speechd-speak-read-mode-line
Pøeèti mode line (@code{speechd-speak-read-mode-line}).  Poznámka:
Tento pøíkaz funguje jen v@tie{}Emacsu verze 21.4 nebo vy¹¹í.

@item C-e i
@kindex C-e i
@findex speechd-speak-last-insertions
Pøeèti poslední pøeètený vlo¾ený text
(@code{speechd-speak-last-insertions}).  To znamená text pøeètený
v@tie{}automaticky mluvících bufferech, viz @xref{Automatické mluvení
bufferù}.
@end table

@cindex prompty po¾adující znak
@cindex read-char
Nìkteré pøíkazy Emacsu vypisují prompt, po kterém èekají na zadaný
znak.  Typickým pøíkladem je pøíkaz @code{ispell-word}.  Pokud
zme¹káte pøedtím pøeètený text, mù¾ete pro jeho zopakování pou¾ít ve
znakovém promptu následující klávesové pøíkazy:

@table @kbd
@item C-e
@findex speechd-speak-last-message
Ten samý pøíkaz jako @kbd{C-e m} vý¹e
(@code{speechd-speak-last-message}).

@item C-a
@findex speechd-speak-last-insertions
Ten samý pøíkaz jako @kbd{C-e i} vý¹e
(@code{speechd-speak-last-insertions}).
@end table

Pokud se vám takové chování znakového promptu nezamlouvá, mù¾ete jej
deaktivovat pomocí následující promìnné:

@vtable @code
@item speechd-speak-allow-prompt-commands
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, povol ve znakových
promptech vý¹e uvedené klávesové pøíkazy.
@end vtable

@node Informující pøíkazy, Øídící pøíkazy, Pøíkazy pro ètení, Pøíkazy
@subsection Informující pøíkazy

@table @kbd
@item C-e C-i b
@findex speechd-speak-buffer-info
@cindex buffer
Pøeèti informace o@tie{}aktuálním bufferu
(@code{speechd-speak-buffer-info}).

@item C-e C-i f
@findex speechd-speak-frame-info
@cindex frame
Pøeèti informace o@tie{}aktuálním frame
(@code{speechd-speak-frame-info}).

@item C-e C-i h
@findex speechd-speak-header-line-info
@cindex header line
Pøeèti obsah header line (@code{speechd-speak-header-line-info}).
Poznámka: Tento pøíkaz funguje jen v@tie{}Emacsu verze 21.4 nebo vy¹¹í.

@item C-e C-i m
@findex speechd-speak-mode-info
@cindex módy
Pøeèti informace o@tie{}aktuálním hlavním a vedlej¹ím módu
(@code{speechd-speak-mode-info}).

@item C-e C-i c
@findex speechd-speak-coding-info
@cindex systémy kódování
Pøeèti informaci o@tie{}aktuálním systému kódování
(@code{speechd-speak-coding-info}).

@item C-e C-i i
@findex speechd-speak-input-method-info
@cindex vstupní metoda
Pøeèti informaci o@tie{}aktuální vstupní metodì
(@code{speechd-speak-input-method-info}).

@item C-e C-i p
@findex speechd-speak-process-info
@cindex proces
Pøeèti stav procesu asociovaného s@tie{}aktuálním bufferem
(@code{speechd-speak-process-info}).
@end table

@node Øídící pøíkazy, Pøíkazy nastavující parametry, Informující pøíkazy, Pøíkazy
@subsection Øídící pøíkazy

@table @kbd
@item C-e q
@kindex C-e q
@findex speechd-speak-toggle-speaking
@cindex zti¹ení
Globálnì pøepni mluvení (@code{speechd-speak-toggle-speaking}).  Pøi
vyvolání s@tie{}prefixovým argumentem pøepni mluvení pouze v@tie{}aktuálním
bufferu.

@item C-e s
@kindex C-e s
@findex speechd-stop
@cindex zastavení
Zastav mluvení aktuální zprávy (@code{speechd-stop}).  Ostatní zprávy
ve frontì Speech Dispatcher budou normálnì pøemluveny.  Je-li pøíkaz
vyvolán s@tie{}prefixovým argumentem, zastav mluvení aktuální zprávy
u@tie{}v¹ech klientù, nejen aktuálního spojení.

@item C-e x
@kindex C-e x
@findex speechd-cancel
@cindex zastavení
Zastav mluvení v¹ech zpráv ve frontì aktuálního spojení.  Je-li pøíkaz
vyvolán s@tie{}univerzálním prefixovým argumentem, zastav ètení v¹ech
zpráv ve v¹ech spojeních.  Je-li pøíkaz vyvolán s@tie{}èíselným
prefixovým argumentem, zastav mluvení v¹ech zpráv v@tie{}Emacsu, ve
kterém byl pøíkaz vyvolán.

@item C-e p
@kindex C-e p
@findex speechd-pause
@cindex pøeru¹ení
Pøeru¹ mluvení --- prozatím ztichni a odlo¾ mluvení aktuální zprávy a¾
do vyvolání pøíkazu pokraèování v@tie{}mluvení
(@code{speechd-pause}).  Je-li pøíkaz vyvolán s@tie{}prefixovým
argumentem, pøeru¹ mluvení u@tie{}v¹ech klientù.

@item C-e SPC
@kindex C-e SPC
@findex speechd-resume
@cindex pokraèování
Pokraèuj v@tie{}pozastaveném mluvení (@code{speechd-resume}).  Je-li
pøíkaz vyvolán s@tie{}prefixovým argumentem, pokraèuj v@tie{}mluvení
u@tie{}v¹ech klientù.

@item C-e 1
@itemx C-e 2
@itemx C-e 3
@itemx C-e 4
@itemx C-e 5
@itemx C-e 6
@itemx C-e 7
@itemx C-e 8
@itemx C-e 9
@kindex C-e 1
@kindex C-e 2
@kindex C-e 3
@kindex C-e 4
@kindex C-e 5
@kindex C-e 6
@kindex C-e 7
@kindex C-e 8
@kindex C-e 9
@findex speechd-speak-key-set-predefined-rate
@cindex rychlost
Nastav jednu z@tie{}pøednastavených rychlostí mluvení
(@code{speechd-speak-key-set-predefined-rate}).  @kbd{C-e 1} nastaví
nejni¾¹í rychlost, @kbd{C-e 5} nastaví støední rychlost a @kbd{C-e 9}
nastaví nejvy¹¹í rychlost.
@end table

@node Pøíkazy nastavující parametry, Hláskování, Øídící pøíkazy, Pøíkazy
@subsection Pøíkazy pro nastavení parametrù
@cindex parametry

Tyto pøíkazy nastavují rùzné vlastnosti øeèového výstupu.  V¹echny
jsou aplikovány pouze na aktuální spojení do Speech Dispatcher (více
informací o@tie{}spojeních do Speech Dispatcher naleznete
v@tie{}@pxref{Hlasy spojení}), pokud nejsou vyvolány
s@tie{}prefixovým argumentem.  Pøi vyvolání s@tie{}èíselným prefixovým
argumentem jsou aplikovány na v¹echna spojení speechd-el, pøi vyvolání
s@tie{}univerzálním prefixovým argumentem jsou aplikována na v¹echna
spojení Speech Dispatcher.

Chcete-li si pro konkrétní buffer vytvoøit zvlá¹tní spojení, které má
své vlastní parametry, mù¾ete tak uèinit následujícím pøíkazem:

@table @kbd
@item C-e C-c
@kindex C-e C-c
@findex speechd-speak-new-connection
@cindex spojení
Nastav pro aktuální buffer dané spojení
(@code{speechd-speak-new-connection}).  Pøíkaz se zeptá na jméno
spojení, mù¾ete zadat buï nové jméno, nebo jméno ji¾ existujícího
spojení.  Pøi obyèejném vyvolání pøíkazu je vám nabídnuto novì
vygenerované jméno spojení, zatímco pøi vyvolání pøíkazu s@tie{}prefixovým
argumentem si mù¾ete vybrat z@tie{}nabídnutých jmen existujících spojení.
@end table

Pøíkazy ovlivòující základní parametry pøevodu textu na øeè:

@table @kbd
@item C-e d l
@kindex C-e d l
@findex speechd-set-language
@cindex jazyk
Nastav jazyk spojení.  Zadejte jej jako kód jazyka dle ISO 639.

@item C-e d .
@kindex C-e d .
@findex speechd-set-punctuation-mode
@cindex interpunkce
Urèi, jak zpracovávat interpunkci, zda ji èíst èi ignorovat.
@code{all} znamená èíst v¹echny interpunkèní znaky, @code{none} je
v¹echny pøeskakuje a @code{some} ète zadanou podmno¾inu interpunkèních
znakù zadaných v@tie{}konfiguraci Speech Dispatcher.

@item C-e d c
@kindex C-e d c
@findex speechd-set-capital-character-mode
@cindex velká písmena
Nastav mód signalizace velkých písmen.  @code{icon} znamená
signalizaci zvukovou ikonou, @code{spell} znamená jejich hláskování
prostøednictvím speciální hláskovací tabulky a @code{none} znamená, ¾e
velká písmena nejsou nijak zvlá¹» signalizována.
@end table

Pøíkazy ovlivòující vlastnosti øeèového výstupu:

@table @kbd
@item C-e d v
@kindex C-e d v
@findex speechd-set-voice
@cindex hlas
Nastav implicitní hlas, který má syntetizér pou¾ívat
(@code{speechd-set-voice}).  Mù¾ete si vybrat nìkterý z@tie{}mno¾iny
hlasù nabízených ve va¹í instalaci Speech Dispatcher.

@item C-e d r
@kindex C-e d r
@findex speechd-set-rate
@cindex rychlost
Nastav rychlost ètení, v@tie{}rozmezí od -100 (nejpomalej¹í) po 100
(nejrychlej¹í) (@code{speechd-set-rate}).  Èasto asi budete
radìji pou¾ívat pøíkaz @code{speechd-speak-key-set-predefined-rate},
dostupný na klávese @kbd{C-e @var{number}}, viz @ref{Øídící pøíkazy}.

@item C-e d p
@kindex C-e d p
@findex speechd-set-pitch
@cindex vý¹ka
Nastav vý¹ku hlasu, v@tie{}rozmezí od -100 (nejni¾¹í) po 100 (nejvy¹¹í)
(@code{speechd-set-pitch}).

@item C-e d V
@kindex C-e d V
@findex speechd-set-volume
@cindex hlasitost
Nastav hlasitost hlasu, v@tie{}rozmezí od -100 (nejni¾¹í) po 100
(nejvy¹¹í) (@code{speechd-set-volume}).
@end table

Pøíkazy ovlivòující øeèový syntetizér:

@table @kbd
@item C-e d o
@kindex C-e d o
@findex speechd-set-output-module
@cindex výstupní modul
Pøepni Speech Dispatcher na zadaný výstupní modul
(@code{speechd-set-output-module}).  Pøíkaz se dotazuje na jméno
¾ádaného výstupního modulu.
@end table

@node Hláskování, Ostatní pøíkazy, Pøíkazy nastavující parametry, Pøíkazy
@subsection Hláskování
@cindex hláskování

@cindex speechd-speak-spell-mode
Hláskovat lze ve speechd-el dvìma zpùsoby.  Prvním je zapnout pro daný
buffer vedlej¹í mód @code{speechd-speak-spell-mode}.  Tento mód je
u¾iteèný, pokud chcete hláskovat vìt¹í mno¾ství textu v@tie{}bufferu.

Druhým zpùsobem hláskování je vyu¾ití následujícího pøíkazu:

@table @kbd
@item C-e C-l
@kindex C-e C-l
@findex speechd-speak-spell
Pøinu» následující pøíkaz hláskovat jím ètený text
(@code{speechd-speak-spell}).  Napøíklad pokud chcete hláskovat slovo
za kurzorem, mù¾ete pou¾ít klávesový pøíkaz @kbd{C-e C-l C-e w}.
@end table

@node Ostatní pøíkazy,  , Hláskování, Pøíkazy
@subsection Ostatní pøíkazy

@kindex C-x C-c
V@tie{}pøípadì, ¾e se Emacs úplnì zblázní a odmítá kvùli chybì speechd-el
nebo u¾ivatelské definici související s@tie{}øeèovým výstupem provádìt
jakékoliv pøíkazy vèetnì @kbd{C-x C-c}, mù¾ete jako poslední pokus
o@tie{}pomoc vyzkou¹et následující pøíkaz:

@table @kbd
@item C-e C-x
@kindex C-e C-x
@findex speechd-unspeak
@cindex vzpamatování se
Pokus se deaktivovat v¹echny módy, háèky a obálky instalované pøíkazem
@code{speechd-speak} (@code{speechd-unspeak}).
@end table

Následující pøíkazy jsou pou¾ívány jen velmi zøídka, povìt¹inou pro
ladící úèely:

@table @kbd
@item C-e z
@kindex C-e z
@findex speechd-repeat
Zopakuj poslední text odeslaný do Speech Dispatcher
(@code{speechd-repeat}).

@item M-x speechd-say-text
@findex speechd-say-text
Zeptej se na text a pøemluv jej.
@end table

@node Konfigurace, Pokroèilá konfigurace, Pøíkazy, U¾ivatelská pøíruèka
@section Konfigurace

@menu
* Konfigurace serveru::         Kam se pøipojit.
* Implicitní priority::         Priority rùzných druhù zpráv.
* Základní mluvení::            Jednoduché volby.
* Automatické mluvení bufferù:: Jak nìkteré buffery rozmluvit ihned.
* Oznamování stavu::            Pøeøíkávání zmìn stavu Emacsu.
* Signalizace::                 Signalizace prázdných zpráv, apod.
* Vlastnosti textu::            Podpora faces a zvlá¹tních èástí textu.
* Jazyky::                      Pou¾ívání více jazykù.
* Hlasy::                       Definice rùzných hlasù.
* Hlasy spojení::               Nastavování parametrù spojení.
* Více spojení::                Odli¹né parametry pro nìkteré módy a buffery.
* Klávesy::                     Pøizpùsobení pøíkazových kláves.
* Módy::                        Háèky vedlej¹ích módù.
* Debugger::                    Potlaèení mluvení v@tie{}debuggeru.
@end menu

@node Konfigurace serveru, Implicitní priority, Konfigurace, Konfigurace
@subsection Konfigurace spojení na Speech Dispatcher server

Nastavení tìchto promìnných umo¾òuje se pøipojit na Speech Dispatcher
bì¾ící na vzdáleném stroji nebo nestandardním portu.

@vtable @code
@item speechd-host
@cindex server
Jméno serveru, na kterém bì¾í Speech Dispatcher, ke kterému se chcete
pøipojit, zadané jako øetìzec.  Implicitní hodnotou je hodnota
shellové promìnné @code{SPEECHD_HOST}, pokud je nastavena, jinak
@code{"localhost"}.

@item speechd-port
@cindex port
Èíslo portu, na který se chcete pøipojit.  Implicitní hodnotou je
hodnota shellové promìnné @code{SPEECHD_PORT}, pokud je nastavena,
jinak obvyklé èíslo portu Speech Dispatcher.

@item speechd-timeout
@cindex timeout
Maximální poèet sekund, po které se má èekat na odpovìï od Speech
Dispatcher.  Je-li tento èas pøekroèen, speechd-el uzavøe pøíslu¹né
spojení.  Za normálních okolností by Speech Dispatcher mìlo odpovídat
na pøíkazu protokolu okam¾itì, av¹ak pokud se pøipojujete na Speech
Dispatcher nìjakým zvlá¹tním zpùsobem po pomalé síti, mù¾ete
potøebovat tento limit zvý¹it.

@item speechd-spdsend
@cindex spdsend
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, musí to být
øetìzec urèující jméno binárky @emph{spdsend} (obvykle
@code{"spdsend"}), která má být pou¾ita pro komunikaci se Speech
Dispatcher.  Je-li hodnotou promìnné @code{nil} nebo pokud je verze
Emacsu vy¹¹í ne¾ 21.3, spdsend se nepou¾ívá.

O@tie{}hodnotu této promìnné se obvykle nemusíte starat.
@end vtable

@node Implicitní priority, Základní mluvení, Konfigurace serveru, Konfigurace
@subsection Implicitní priority
@cindex priority

Po¹le-li nìjaká funkce speechd-el na Speech Dispatcher zprávu bez
explicitnì specifikované priority dané zprávy, pøiøadí se zprávì
priorita dle obsahu ní¾e uvedených promìnných.  Zmìnou jejich hodnot
mù¾ete dosáhnout zajímavých efektù.  Napøíklad zmìnou hodnoty promìnné
@code{speechd-default-key-priority} z@tie{}@code{notification} na
@code{message} zaøídíte, ¾e v¹echny napsané znaky budou øeèeny a budou
pøeru¹ovat obvyklé ètení textù.

V¹echny tyto promìnné mohou nabývat nìkteré z@tie{}následujících hodnot:
@code{important}, @code{message}, @code{text}, @code{notification},
@code{progress}.  Tyto hodnoty odpovídají prioritám Speech Dispatcher,
více podrobností naleznete v@tie{}manuálu Speech Dispatcher.

@vtable @code
@item speechd-default-text-priority
Implicitní priorita vìt¹iny textových zpráv.

@item speechd-default-sound-priority
Implicitní priorita zvukových ikon.

@item speechd-default-char-priority
Implicitní priorita hláskovaných znakù.

@item speechd-default-key-priority
Implicitní priorita znakù napsaných na klávesnici.
@end vtable

@node Základní mluvení, Automatické mluvení bufferù, Implicitní priority, Konfigurace
@subsection Základní konfigurace mluvení

@vtable @code
@item speechd-speak-deleted-char
@cindex mazání
Urèuje, který znak má být pøeèten pøi mazání znaku.  Je-li hodnotou
nìco jiného ne¾ @code{nil}, pøeèti smazaný znak, jinak pøeèti sousední
znak.

@item speechd-speak-buffer-name
@cindex buffery
Pøepínáte-li se do jiného bufferu a hodnotou této promìnné je nìco
jiného ne¾ @code{nil}, je pøeèteno jméno nového bufferu.  Je-li
hodnotou promìnné symbol @code{text}, ète se kromì jména bufferu je¹tì
text jeho øádku od pozice kurzoru do konce øádku.  Je-li hodnotou
promìnné @code{nil}, je pøeèten jen text, beze jména bufferu.

@item speechd-speak-whole-line
@cindex ètení øádkù
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, èti pøi pøesunu na
jinou pozici celý øádek.  Jinak èti øádek jen od pozice kurzoru do
konce øádku.

@item speechd-speak-on-minibuffer-exit
@cindex minibuffer
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, speechd-el ète
po návratu z@tie{}minibufferu nebo rekurzivní editaèní úrovnì text
okolo kurzoru, není-li ke ètení nic lep¹ího.

@item speechd-speak-read-command-keys
@cindex pøíkazové klávesy
@cindex klávesy
Tato promìnná definuje, v@tie{}jakých situacích jsou èteny pøíkazové
klávesy aktuálního pøíkazu.  Je-li hodnotou promìnné @code{t},
pøíkazové klávesy jsou èteny v¾dy.  Je-li hodnotou promìnné
@code{nil}, nejsou èteny nikdy.  Je-li hodnotou promìnné seznam, mù¾e
obsahovat jeden nebo více z@tie{}následujících symbolù
identifikujících situace, za kterých mají být klávesy pøíkazu
pøeèteny:

@table @code
@item movement
Pøeèti pøíkazové klávesy, jestli¾e do¹lo k@tie{}pøesunu kurzoru, ale
nebyl modifikován obsah bufferu.

@item modification
Byl modifikován obsah bufferu, nedo¹lo k@tie{}pøesunu kurzoru.

@item movement-modification
Byl modifikován obsah bufferu a do¹lo k@tie{}pøesunu kurzoru.
@end table

Je-li hodnotou promìnné @code{t}, pøíkazové klávesy jsou èteny pøed
provedením pøíkazu.  Jinak jsou pøeøíkány a¾ po provedení pøíkazu,
proto¾e je tøeba nejprve zjistit, zda do¹lo k@tie{}modifikaci obsahu
bufferu a pøesunu kurzoru.

@item speechd-speak-ignore-command-keys
@cindex pøíkazové klávesy
@cindex klávesy
Seznam pøíkazù, u@tie{}nich¾ nemají být pøíkazové klávesy nikdy èteny.

@item speechd-speak-read-command-name
@cindex jméno pøíkazu
Je-li hodnotou nìco jiného ne¾ @code{nil}, èti v@tie{}situacích
definovaných promìnnou @code{speechd-speak-read-command-keys} místo
kláves pøíkazu jeho jméno.

@item speechd-speak-message-time-interval
@cindex hlá¹ení
@cindex opakování
Minimální poèet vteøin, po kterých smí být hlá¹ení zopakováno.  Je-li
aktuální hlá¹ení stejné jako hlá¹ení pøedchozí, není pøeøíkáno, pokud
neuplynul aspoò zde definovaný èas od posledního pøeøíkaného hlá¹ení.
@end vtable

@node Automatické mluvení bufferù, Oznamování stavu, Základní mluvení, Konfigurace
@subsection Automatické mluvení bufferù
@cindex buffery
@cindex vkládaný text

Nìkdy je u¾iteèné zaèít pøemlouvat obsah bufferu i@tie{}bez explicitního
po¾adavku u¾ivatele.  Napøíklad je-li vyvolán pøíkaz nápovìdy,
u¾ivatel si obvykle chce ihned poté pøeèíst její text.  Následující
promìnné definují seznam jmen bufferù, které mají být automaticky
pøemluveny, jestli¾e jsou viditelné v@tie{}nìkterém z@tie{}oken aktuálního rámce
a jejich obsah byl bìhem posledního u¾ivatelského pøíkazu zmìnìn.

@vtable @code
@item speechd-speak-auto-speak-buffers
Obsah tìchto bufferù je pøemluven za vý¹e uvedených podmínek po
provedení pøíkazu, jestli¾e není k@tie{}pøemluvení nic jiného (napøíklad
pod kurzorem pøi pøesunu kurzoru na jinou pozici).

@item speechd-speak-force-auto-speak-buffers
Stejné jako @code{speechd-speak-auto-speak-buffers} a¾ na to, ¾e obsah
bufferu je pøemluven vynucenì, i@tie{}kdy¾ by mohlo být pøemluveno nìco
jiného.
@end vtable

Následující promìnné urèují, jak nakládat s@tie{}texty vlo¾enými bìhem
provádìní u¾ivatelských pøíkazù.  Týkají se pouze novì vlo¾ených
textù, neovlivòují zpracování smazaných textù.  Navíc tyto volby
neovlivòují texty vlo¾ené bìhem provádìní pøíkazù, které speechd-el
anebo u¾ivatelské definice zpracovávají speciálním zpùsobem, jako je
napøíklad pøípad pøíkazu @code{self-insert-command}.

@vtable @code
@item speechd-speak-buffer-insertions
Urèuje, zda má být automaticky èten text vkládaný v@tie{}aktuálním bufferu.
Hodnotou promìnné mù¾e být nìkterý z@tie{}následujících symbolù:

@table @code
@item nil
Neèti ¾ádné vlo¾ené texty.

@item t
Èti v¹echny vlo¾ené texty.

@item one-line
Èti pouze první øádky vlo¾ených textù.

@item whole-buffer
Pokud byl buffer jakkoliv modifikován, pøeèti jej celý.
@end table

@item speechd-speak-insertions-in-buffers
Seznam jmen bufferù, ve kterých jsou vkládané texty èteny automaticky,
bez ohledu na to, zda jde o@tie{}aktuální buffer a bez ohledu na hodnotu
promìnné @code{speechd-speak-buffer-insertions}.

@item speechd-speak-priority-insertions-in-buffers
Seznam jmen bufferù, ve kterých jsou vkládané texty èteny automaticky
okam¾itì po svém vlo¾ení, ne a¾ po dokonèení provádìného pøíkazu, jako
je tomu v@tie{}pøípadì promìnné @code{speechd-speak-insertions-in-buffers}.
Tato vlastnost je typicky u¾iteèná v@tie{}comint bufferech.

@item speechd-speak-align-buffer-insertions
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, je vkládaný text
pøed svým pøeètením roz¹íøen k@tie{}zaèátku prvního slova, které je alespoò
zèásti obsa¾eno ve vlo¾eném textu.  To je u¾iteèné zejména v@tie{}pøípadì
doplòovacích funkcí.
@end vtable

Jestli¾e pøíkaz modifikoval aktuální buffer a pøesunul kurzor na úplnì
jinou pozici, nová pozice kurzoru není v@tie{}øeèovém výstupu
nijak vyznaèena.  To lze zmìnit prostøednictvím následující promìnné:

@vtable @code
@item speechd-speak-movement-on-insertions
Je-li hodnotou promìnné @code{t}, pøeèti text okolo nové pozice
kurzoru, i@tie{}kdy¾ byl aktuální buffer modifikován.  Je-li hodnotou
promìnné @code{read-only}, èti jej jen v@tie{}read-only bufferech.
Je-li hodnotou @code{nil}, neèti jej.
@end vtable

@node Oznamování stavu, Signalizace, Automatické mluvení bufferù, Konfigurace
@subsection Oznamování zmìn stavu

speechd-el mù¾e èíst informaci o@tie{}aktuálním stavu Emacsu, jako
jméno aktuálního bufferu, hlavní a vedlej¹í módy nebo jiné atributy
bufferu, viz @xref{Informující pøíkazy}.  Zmìny stavu Emacsu mohou být
oznamovány automaticky, v@tie{}závislosti na u¾ivatelské konfiguraci:

@vtable @code
@item speechd-speak-state-changes
Seznam identifikátorù zmìn stavu Emacsu, které mají být automaticky
oznamovány.  Jako identifikátory zmìny stavu lze pou¾ít následující
symboly:

@table @code
@item buffer-name
@item buffer-identification
(jen v@tie{}Emacsu 21.4 nebo vy¹¹ím)
@item buffer-modified
@item buffer-read-only
@item frame-name
@item frame-identification
(jen v@tie{}Emacsu 21.4 nebo vy¹¹ím)
@item header-line
(jen v@tie{}Emacsu 21.4 nebo vy¹¹ím)
@item major-mode
@item minor-modes
@item buffer-file-coding
@item terminal-coding
@item input-method
@item process
@end table

@item speechd-speak-display-modes
Seznam vedlej¹ích módù, u@tie{}nich¾ je místo jejich jména pøeøíkáván
jejich zobrazený øetìzec.  To mù¾e být u¾iteèné v@tie{}pøípadech, kdy
je zobrazený øetìzec struènìj¹í ne¾ jméno módu nebo kdy¾ je zobrazený
øetìzec zmìnìn, ani¾ by byl zmìnìn samotný mód.
@end vtable

@node Signalizace, Vlastnosti textu, Oznamování stavu, Konfigurace
@subsection Signalizace

Nìkteré situace mohou být signalizovány zvukovými ikonami.
Následující promìnná zapíná nebo vypíná pøeddefinované signalizace.
O@tie{}tom, jak si definovat vlastní signalizace, se mù¾ete doèíst
v@tie{}sekci @ref{Pokroèilá konfigurace}.

@vtable @code
@item speechd-speak-signal-events
Seznam symbolù, obsahující jména událostí, které mají být
signalizovány zvukovou ikonou.  Podporována jsou následující jména
událostí:

@table @code
@item start
Start nebo restart speechd-el.

@item empty
@cindex prázdný text
Prázdný text v@tie{}rùzných situacích.

@item beginning-of-line
@cindex øádek
@cindex zaèátek øádku
Dosa¾ení zaèátku øádku po pøíkazech @code{forward-char} a
@code{backward-char}.

@item end-of-line
@cindex konec øádku
Dosa¾ení konce øádku po pøíkazech @code{forward-char} a
@code{backward-char}.

@item minibuffer
Vstup do minibufferu.

@item message
Následují hlá¹ení v@tie{}echo area.
@end table
@end vtable

@node Vlastnosti textu, Jazyky, Signalizace, Konfigurace
@subsection Vlastnosti textu
@cindex vlastnosti textu
@cindex faces
@cindex kurzor
@cindex pohyb

Implicitní chování speechd-el je takové, ¾e po pøíkazu, který zpùsobí
pøesun kurzoru na jinou pozici, pøeète aktuální øádek.  Pokud je v¹ak
pozice kurzoru obklopena textem, který má nìjaké vlastnosti (text
properties), typicky face, ale mù¾e jít o@tie{}jakékoliv jiné vlastnosti,
speechd-el dovede pøeèíst pouze tu èást textu pod kurzorem, která má
shodné vlastnosti.

Pokud je navíc zapnut font lock mód, faces mohou být mapovány na rùzné
hlasy.

@vtable @code
@item speechd-speak-by-properties-on-movement
Metoda výbìru èásti textu, která má být pøeètena po pøesunu kurzoru.
Promìnná mù¾e nabývat nìkteré z@tie{}následujících hodnot:

@table @asis
@item @code{nil}
Vlastnosti textu (text properties) nejsou nijak zohledòovány.

@item @code{t}
Jsou zohledòovány v¹echny vlastnosti textu.

@item seznam faces
Z@tie{}vlastností textu jsou zohledòována pouze daná faces.
@end table

@item speechd-speak-by-properties-always
Seznam pøíkazù, které v¾dy zohledòují vlastnosti textu, a@tie{}to
i@tie{}v@tie{}pøípadì ¾e hodnota promìnné
@code{speechd-speak-by-properties-on-movement} je @code{nil}.

@item speechd-speak-by-properties-never
Seznam pøíkazù, které nikdy nezohledòují vlastnosti textu, a@tie{}to ani
v@tie{}pøípadì ¾e hodnota promìnné
@code{speechd-speak-by-properties-on-movement} není @code{nil}.

@item speechd-speak-faces
Tato promìnná umo¾òuje zajistit vyvolání akcí v@tie{}pøípadì, kdy kurzor po
provedení u¾ivatelského pøíkazu skonèí na urèitém face.  Hodnotou
promìnné je asociativní seznam s@tie{}prvky tvaru @code{(@var{face}
. @var{akce})}.

Jestli¾e pøíkaz pøesouvající kurzor zanechá kurzor na @var{face} a na
pøíkaz není explicitnì navì¹eno ¾ádné mluvení, je vyvolána
@var{akce}.  Je-li @code{akce} øetìzcem, je tento øetìzec pøemluven.
Je-li @code{akce} funkcí, je tato funkce zavolána, bez argumentù.

@item speechd-face-voices
Mapování faces na hlasy.  Hodnotou promìnné je asociativní seznam
s@tie{}prvky tvaru @code{(@var{face} . @var{hlas})}, kde @var{face} je face
a @var{hlas} je jméno hlasu definované v@tie{}promìnné
@code{speechd-voices}, viz @xref{Hlasy}.  Ka¾dé face je pøemluveno
odpovídajícím hlasem.  Pokud pro nìjaké face není hlas v@tie{}této promìnné
definovat, je toto face pøemluveno aktuálním hlasem.

Pozor, toto mapování se uplatní jen tehdy, je-li zapnut font lock mód.
@end vtable

@node Jazyky, Hlasy, Vlastnosti textu, Konfigurace
@subsection Pou¾ívání více jazykù
@cindex jazyky

speechd-el je mo¾no pou¾ívat s@tie{}vícero jazyky.  Nicménì proces
volby jazyka nemù¾e být snadno automatizováno, proto¾e bì¾ný text
neobsahuje ¾ádnou informaci o@tie{}svém jazyce.  Tak¾e pokud chcete
pou¾ívat speechd-el s@tie{}výstupem ve více jazycích, musíte
speechd-el napovídat.

@vindex speechd-language
@cindex RFC 1766
Základním prostøedkem pro sdìlení informace o@tie{}aktuálním jazyku je
promìnná @code{speechd-language}.  Poka¾dé, kdy¾ chce speechd-el øíct
nìjaký text, podívá se na tuto promìnnou, zda neobsahuje kód jazyka.
Pokud její hodnota není @code{nil}, musí to být øetìzec obsahující kód
jazyka dle RFC@tie{}1766 a speechd-el pøeète text v@tie{}odpovídajícím
jazyce.

Vìt¹inou asi budete chtít nastavit tuto promìnnou v@tie{}konkrétním
souboru, viz @ref{File Variables,,,emacs,GNU Emacs Manual}, nebo jako
lokální promìnnou bufferu, viz @ref{Locals,,,emacs,GNU Emacs Manual},
v@tie{}rùzných mode hooks, see @ref{Hooks,,,emacs,GNU Emacs Manual}.

@findex speechd-language
@cindex text property @code{language}
Pokud má text vlastnost (property) @code{language} obsahující kód
jazyka dle RFC@tie{}1766, je pøemluven v@tie{}odpovídajícím jazyce bez
ohledu na v¹echna ostatní nastavení.  K@tie{}dispozici je funkce
@code{speechd-language}, která v@tie{}elispových programech umístí
tuto textovou vlastnost na øetìzec.

Jinou dobrou cestou, jak pou¾ívat více jazykù, je pou¾ívat více
spojení pro oddìlení jazykovì závislých bufferù nebo módù, viz
@ref{Více spojení}, a nastavit pro ka¾dé z@tie{}tìchto spojení
parametr @code{language}, viz @ref{Hlasy spojení}.

Pokud u¾ není mo¾ná ¾ádná lep¹í cesta, je mo¾né jazyky nastavovat
podle aktuální vstupní metody:

@vtable @code
@item speechd-speak-input-method-languages
Asociativní seznam mapující vstupní metody na jazyky.  Ka¾dý
z@tie{}prvkù seznamu má podobu @code{(@var{input-method-name} .
@var{language})}, kde @var{input-method-name} je jméno metody jako
øetìzec a @var{language} je ISO kód jazyka akceptovaný SSIP.  Jestli¾e
je aktuální vstupní metoda v@tie{}seznamu pøítomna, je vybrán
odpovídající jazyk, není-li pøebit jiným nastavením.
@end vtable

@node Hlasy, Hlasy spojení, Jazyky, Konfigurace
@subsection Definice hlasù
@cindex parametry

Ve speechd-el lze definovat speciální hlasy, které pak mohou být
vyu¾ívány v@tie{}rùzných situacích, napøíklad pro pøemlouvání rùzných
faces rùznými hlasy (@pxref{Vlastnosti textu}) nebo pro nastavení
rùzných re¾imù ètení interpunkce pro rùzné druhy bufferù (@pxref{Více
spojení}).  Hlasy ve speechd-el neurèují jen základní charakteristiku
hlasu, ale také vlastnosti øeèi jako vý¹ku èi rychlost a zvlá¹tní
vlastnosti jako re¾im ètení interpunkce nebo signalizaci velkých
písmen.

Definice hlasù je obsa¾ena v@tie{}následující promìnné:

@vtable @code
@item speechd-voices
Asociativní seznam identifikátorù hlasù a jejich parametrù.

Ka¾dý prvek seznamu má podobu @code{(@var{voice-id} .
@var{parameters})}, kde @var{voice-id} je symbo, pod kterým bude hlas
dostupný a @var{parameters} je asociativní seznam identifikátorù
parametrù a jejich hodnot.  Pøípustná jména parametrù jsou následující
symboly: @code{language}, @code{gender}, @code{age}, @code{style},
@code{name}, @code{rate}, @code{pitch}, @code{volume},
@code{punctuation-mode}, @code{capital-character-mode},
@code{message-priority}, @code{output-module}.

@code{name} je øetìzec identifikující jméno hlasu Speech Dispatcher.
Není-li uveden, pak jsou pro volbu hlasu rozhodující parametry
@code{gender}, @code{age} a @code{style}.  @code{gender} mù¾e být
jeden ze symbolù @code{male}, @code{female}, @code{neutral}.
@code{age} mù¾e být jeden ze symbolù @code{middle-adult},
@code{child}. @code{neutral}.  @code{style} mù¾e být jedno
z@tie{}èísel @code{1}, @code{2}, @code{3} (hodnoty parametru
@code{style} se v@tie{}budoucnu pravdìpodobnì zmìní).

Parametr @code{message-priority} nastavuje prioritu v¹ech zpráv
øíkaných daných hlasem.  Jeho hodnotou mù¾e být kterýkoliv ze symbolù
identifikujících prioritu zprávy.

Pro povolené hodnoty ostatních parametrù viz odpovídající
@code{speechd-set-*} funkce.

Hlas pojmenovaný @code{nil} je zvlá¹tní, definuje implicitní hlas.
Explicitní definice jeho parametrù je nepovinná.
@end vtable

@node Hlasy spojení, Více spojení, Hlasy, Konfigurace
@subsection Hlasy spojení
@cindex hlasy

S@tie{}pomocí následující promìnné si mù¾ete nechat automaticky
nastavit rùzné parametry spojení, jako rychlost øeèi, jazyk, atd.
speechd-el mù¾e mít na Speech Dispatcher otevøeno více spojení,
definovaných dle rùzných kritérií (@pxref{Více spojení}).  Rùzným
spojením pak mù¾ete nastavit rùzné parametry, v@tie{}závislosti na
jménu spojení, a@tie{}mù¾ete také nastavit implicitní parametry
spoleèné pro v¹echna spojení.

@vtable @code
@item speechd-connection-parameters
Asociativní seznam jmen spojení a odpovídajících hlasù.  Ka¾dý prvek
seznam má podobu @code{(@var{connection-name} . @var{voice})}, kde
@var{connection-name} je jméno spojení ve formì øetìzce a
@var{voice} je identifikátor hlasu definovaného v@tie{}promìnné
@code{speechd-voices}.

Pro spojení, která nejsou v@tie{}této promìnné definována se pou¾ívá
implicitní hlas, jeho¾ jméno je @code{nil}.
@end vtable

Aby se nastavení hodnoty této promìnné plnì projevilo, musí být
otevøená spojení znovuotevøena.  Nepou¾íváte-li konfiguraèní rozhraní
Emacsu (customize), musíte pro zaji¹tìní znovuotevøení spojení zavolat
pøíkaz @kbd{C-u M-x speechd-speak}.

Jako malou pomùcku pro nastavení hlasu spojení a jeho parametrù je
mo¾né pou¾ít tento pøíkaz:

@table @kbd
@item C-e C-a
@kindex C-e C-a
@findex speechd-add-connection-settings
Ulo¾ aktuální parametry spojení do zadaného hlasu v@tie{}promìnné
@code{speechd-voices} s nastav tento hlas pro aktuální spojení
v@tie{}promìnné @code{speechd-connection-voices}.

Nezapomeòte, ¾e pokud chcete zachovat nový obsah tìchto promìnných,
musíte si je sami ulo¾it, pøíkaz to nedìlá.
@end table

@node Více spojení, Klávesy, Hlasy spojení, Konfigurace
@subsection Více spojení
@cindex spojení

speechd-el mù¾ete øíct, aby pro urèité buffery nebo hlavní módy
pou¾ívalo oddìlená spojení na Speech Dispatcher.  To v@tie{}zásadì umo¾òuje
nezávislé nastavení rùzných parametrù øeèového výstupu pro tyto
buffery a hlavní módy, jak ruèní, tak prostøednictvím konfigurace
(@pxref{Hlasy spojení}).

Ka¾dé spojení na Speech Dispatcher má své vlastní jedineèné jméno.
speechd-el implicitnì pou¾ívá spojení nazvané @code{"default"}.  Pro
vytvoøení oddìleného spojení staèí pouze nechat v@tie{}urèitých situacích
speechd-el vybrat jiné jméno spojení.  Zpùsob výbìru spojení je
definován promìnnou @code{speechd-speak-connections}.

@vtable @code
@item speechd-speak-connections
Asociativní seznam mapující hlavní módy a buffery na spojení.  Ka¾dý
prvek seznamu je tvaru @code{(@var{mód-nebo-buffer}
. @var{jméno-spojení})}.

Kdy¾ chce speechd-el poslat zprávu, porovnává momentální prostøedí
s@tie{}@var{mód-nebo-buffer}.  @var{mód-nebo-buffer} smí být jedním
z@tie{}následujících objektù, od nejvy¹¹í priority po nejni¾¹í:

@itemize @bullet
@item
seznam, reprezentující volání funkce, která musí vrátit jinou hodnotu
ne¾ @code{nil}, právì kdy¾ má být pou¾it pøíslu¹ný prvek asociativního
seznamu

@item
jméno bufferu

@item
symbol @code{:minibuffer}, reprezentující minibuffer

@item
symbol hlavního módu

@item
@code{nil}, reprezentující nebufferové objekty, napø. echo area

@item
@code{t}, reprezentující implicitní hodnotu, kdy¾ není aplikovatelný
¾ádný jiný prvek
@end itemize

Jestli¾e urèité situaci odpovídá více prvkù, je pou¾it prvek
s@tie{}nejvy¹¹í prioritou.

@var{jméno-spojení} je libovolný neprázdný øetìzec urèující jméno
po¾adovaného spojení.  Není-li otevøeno ¾ádné spojení daného jména, je
automaticky vytvoøeno v@tie{}okam¾iku, kdy do nìj má být nìco zasláno.
@end vtable

@node Klávesy, Módy, Více spojení, Konfigurace
@subsection Klávesy
@cindex klávesy
@cindex prefixová klávesa
@cindex klávesová mapa

Pøíkazové klávesy speechd-el jsou definovány promìnnou
@code{speechd-speak-prefix} a klávesovou mapou
@code{speechd-speak-mode-map}.

@vtable @code
@item speechd-speak-prefix
Tato promìnná definuje prefixovou klávesu pøíkazù speechd-el, kterou
je implicitnì @kbd{C-e}.  Jestli¾e tuto promìnnou zmìníte a¾ po
nastartování mluvení prostøednictvím pøíkazu @code{speechd-speak} a
nenastavujete ji prostøednictvím konfiguraèního rozhraní Emacsu
(customize), musíte, aby se zmìna projevila, pøíkaz
@code{speechd-speak} spustit znovu.

@item speechd-speak-mode-map
Tato klávesová mapa urèuje mapování kláves speechd-el následujících za
prefixovou klávesou.  Mù¾ete v@tie{}ní klávesy nastavovat obvyklým
zpùsobem, napø.

@lisp
(define-key speechd-speak-mode-map "t" 'speechd-say-text)
@end lisp

pøiøadí pøíkaz @code{'speechd-say-text} klávese @code{C-e t} (je-li
prefixovou klávesou @code{C-e}).
@end vtable

@node Módy, Debugger, Klávesy, Konfigurace
@subsection Háèky ve vedlej¹ích módech
@cindex vedlej¹í módy
@cindex háèky

speechd-el poskytuje vedlej¹í mód, který zapíná a vypíná mluvení,
@xref{Spu¹tìní øeèového výstupu}.  Prostøednictvím následujícího háèku
si mù¾ete nechat provést vlastní akce pøi vstupu do tohoto módu:

@vtable @code
@item speechd-speak-mode-hook
Háèek spu¹tìný pøi zapnutí vedlej¹ího módu speechd-speak.
@end vtable

@node Debugger,  , Módy, Konfigurace
@subsection Ladìní speechd-el
@cindex debugger
@cindex ladìní

Pokud se pokou¹íte øeèový výstup ladit, mù¾ete narazit na problém
rekurzivního vyvolávání ladìných funkcí v@tie{}elispových debuggerech.
Tomu lze ve speechd-el zabránit zákazem mluvení v@tie{}debuggerech:

@vtable @code
@item speechd-speak-in-debugger
Je-li hodnotou promìnné nìco jiného ne¾ @code{nil}, funkce
automatického øeèového výstupu nemluví v@tie{}elispových debuggerech.
@end vtable

@node Pokroèilá konfigurace, Potí¾e, Konfigurace, U¾ivatelská pøíruèka
@section Definice vlastních reakcí na pøíkazy
@cindex roz¹íøení

Psaní vlastních reakcí na pøíkazy obecnì vy¾aduje znalost programování
v@tie{}Elispu.  Nemusíte se v¹ak dìsit, základní vìci si mù¾ete nastavit
i@tie{}bez toho, staèí se øídit zde uvedenými instrukcemi.

speechd-el umo¾òuje øíct text, pøehrát zvukovou ikonu nebo zavolat
libovolný elispový výraz pøed nebo po provedení pøíkazu nebo funkce.
Pro tyto úèely jsou k@tie{}dispozici dvì makra, která zajistí, ¾e se kromì
vlastní akce provede v¹e, co je nutno:

@ftable @code
@item speechd-speak-command-feedback @var{pøíkaz} @var{pozice} @var{reakce}
Definuj reakci na @var{pøíkaz}.  @var{pøíkaz} je jméno interaktivní
funkce (pou¾ijte @kbd{C-h C-c} pro zji¹tìní jména pøíkazu navázaného
na urèitou klávesu).

@var{pozice} mù¾e být jeden ze symbolù @code{before} nebo @code{after}
pro vyvolání reakce pøed (@code{before}) nebo poté (@code{after}), co
je pøíkaz proveden.

@code{reakce} mù¾e být øetìzec nebo jakýkoliv elispový výraz.
Jedná-li se o@tie{}øetìzec (text uzavøený v@tie{}uvozovkách), definuje text
k@tie{}pøeøíkání nebo zvukovou ikonu k@tie{}pøehrání.  Jestli¾e øetìzec zaèíná
hvìzdièkou (@code{*}), urèuje jméno zvukové ikony (hvìzdièka není
souèástí jména), jinak se jedná o@tie{}normální text.

Pøíklad:
@cindex @code{suspend-emacs}

@lisp
(speechd-speak-command-feedback suspend-emacs before "Suspenduji Emacs!")
@end lisp

Tento øádek elispového kódu mù¾ete vlo¾it do svého @file{~/.emacs},
èím¾ si zajistíte upozornìní o@tie{}vyvolání pøíkazu @code{suspend-emacs}
(obvykle navázaného @kbd{C-z}).

@item speechd-speak-function-feedback @var{funkce} @var{pozice} @var{reakce}
Toto je stejné jako @code{speechd-speak-command-feedback} a¾ na to, ¾e
@var{reakce} je vyvolána kdykoliv je vyvolána @code{funkce}, a» u¾
interaktivnì èi nikoliv.  Navíc @code{funkce} mù¾e být jakákoliv
funkce, nejen interaktivní pøíkaz.
@end ftable

@emph{Prosím pozor:}

@itemize @bullet
@item
Kvùli urèitému nedostatku Emacsu nemusí popsaný mechanismus reakcí
správnì fungovat pro vestavìné funkce.

@item
Pokud si definujete vlastní reakce na funkce bez pou¾ití uvedených
maker, buïte opatrní.  Uvedená makra definují kód zaji¹»ující, ¾e se
nic neøíká v@tie{}pøípadì vypnutého @code{speechd-speak-mode}, a@tie{}podobná
opatøení.  Pokud tato makra nepou¾íváte, musíte si tato opatøení
zajistit sami.
@end itemize

@node Potí¾e, Tipy, Pokroèilá konfigurace, U¾ivatelská pøíruèka
@section Potí¾e, se kterými se mù¾ete setkat
@cindex potí¾e

@itemize @bullet
@cindex Info
@item
@emph{Proè se nepøeøíkávají nìkteré polo¾ky menu v@tie{}Info?}

Je to zpùsobeno tím, jakým zpùsobem Emacs umis»uje faces na polo¾ky
menu.  Problém lze obejít nastavením hodnoty promìnné
@code{Info-fontify-maximum-menu-size} na @code{0}.

@cindex upozornìní na události
@cindex diáø
@item
@emph{Jakým zpùsobem lze Emacs pøimìt k@tie{}pøeøíkávání upozornìní na
události (appointments)?}

Nastavte promìnnou @code{appt-msg-window} na @code{nil}.  Takté¾ mù¾e
být u¾iteèné pøidat do promìnné @code{speechd-speak-auto-speak-buffer}
øetìzec @code{"diary"}.

@cindex w3m-el
@cindex URL
@item
@emph{Jak zabránit vypisování URL pøi pohybu po lincích ve w3m-el?}

Pøidejte si do svého @file{~/.emacs} následující kód:

@lisp
(defadvice w3m-print-this-url (around my-w3m-print-this-url activate)
  (when (eq this-command 'w3m-print-this-url)
    ad-do-it))
@end lisp

@cindex opakované ètení
@item
@emph{V@tie{}nìkterých situacích, kdy je po provedení pøíkazu èten
modifikovaný text, je tento text èten po kusech a nìkteré
z@tie{}tìchto kusù jsou opakovány.}

Obsah bufferu se v@tie{}elispových programech mù¾e mìnit mnoha rùznými
zpùsoby.  speechd-el nemù¾e uspokojivì o¹etøit v¹echny mo¾né takové
postupy.  Pokud máte rozumný nápad, jak v@tie{}nìjaké situaci vylep¹it
ètení zmìn textu v@tie{}bufferu, øeknìte nám o@tie{}tom.

Pokud na tento problém narazíte u@tie{}nìkterého èasto provádìného
pøíkazu, mù¾ete si pro tyto pøíkazy definovat svoji vlastní øeèovou
odezvu.  Více informací o@tie{}mo¾nostech definic vlastní øeèové
odezvy naleznete v@tie{}sekci @ref{Pokroèilá konfigurace}.

@item
@cindex prodlevy
@cindex garbage collection
@cindex @code{gc-cons-threshold}
@emph{Pøedtím, ne¾ se po pøíkazu nìco øekne, se obèas objevuje malá
prodleva (pøibli¾nì jednosekundová).}

Mo¾ná, ¾e Emacs bìhem prodlevy provádí garbage collection.  Zkuste
zvý¹it hodnotu promìnné @code{gc-cons-threshold}, tøeba na 4000000.
Mù¾e to celkový výkon zvý¹it nebo sní¾it, v@tie{}závislosti na va¹em
prostøedí a konkrétních po¾adavcích.

Jste-li zku¹eným elispovým hackerem a doká¾ete zjistit, proè
speechd-el produkuje významné mno¾ství dat zpùsobujících zvý¹ení
frekvence provádìní garbage collection a jak nìco v@tie{}tomto smìru
vylep¹it, va¹e pomoc je vítána!

@item
@emph{Pøi pøidr¾ení klávesy @kbd{C-n} obrazovka na chvíli zamrzne a
kurzor se nepohybuje.}

Je-li Emacs zamìstnaný nìjakou èinností, není obecnì provádìna
aktualizace obrazovku.  speechd-el je v@tie{}kombinaci s@tie{}vy¹¹í rychlostí
automatického opakování kláves schopno dosáhnout takového stavu
pomìrnì snadno.  Pøedstavuje-li to pro vás skuteèný problém, mù¾ete si
sní¾it rychlost autorepeatu nebo poøídit rychlej¹í poèítaè.

Samozøejmì jsou vítány jakékoliv tipy, jak zvý¹it rychlost speechd-el.
@end itemize

@node Tipy, Oznamování chyb, Potí¾e, U¾ivatelská pøíruèka
@section U¾iteèné emacsové tipy

Nezapomeòte, ¾e Elisp vám umo¾òuje definovat si spoustu u¾iteèných
funkcí.  Typicky si mù¾ete definovat pøíkazy oznamující nìjaké
informace, které jsou snadno identifikovatelné na emacsové obrazovce,
ale které nejsou tak dobøe rozpoznatelné v@tie{}øeèovém výstupu.

Nìkolik pøíkladù:

@itemize @bullet
@item
@emph{Oznamování aktuálního data v@tie{}kalendáøi:}

@cindex den v@tie{}kalendáøi
@lisp
(defun report-day ()
  (interactive)
  (message "%s" (calendar-date-string (calendar-cursor-to-date t))))
@end lisp

@item
@emph{Výpis aktuálních upozornìní na události z@tie{}diáøe:}

@cindex upozornìní na události
@lisp
(defun report-current-appointments ()
  (interactive)
  (let ((appt-now-displayed nil))
    (appt-check)))
@end lisp
@end itemize

@node Oznamování chyb,  , Tipy, U¾ivatelská pøíruèka
@section Jak oznamovat chyby speechd-el nebo Speech Dispatcher
@cindex chyby

Narazíte-li na chybu speechd-el, mù¾ete pro její oznámení pou¾ít
následující pøíkaz.  Ale ne¾ tak uèiníte, pøeètìte si prosím celý text
této sekce, aby vámi oznámená chyba mohla být øe¹ena co
nejefektivnìji.

@ftable @kbd
@item M-x speechd-bug
@findex speechd-bug
Oznam chybu speechd-el nebo Speech Dispatcher.  Pøíkaz se zeptá na
urèité informaci a pak se zeptá, zda chybu doká¾ete zreprodukovat.
Pokud doká¾ete, odpovìzte @kbd{y} a zaènìte chybu reprodukovat.
Ihned, jakmile je chyba zreprodukována, stisknìte @kbd{C-e C-f}.
Potom mù¾ete (a@tie{}mìli byste) dále zeditovat vygenerovaný e-mail a
odeslat jej obvyklým zpùsobem.

@item M-x speechd-bug-reproduce
@findex speechd-bug-reproduce
@kindex C-e C-f
Zahaj reprodukci chyby speechd-el nebo Speech Dispatcher.  Od tohoto
okam¾iku jsou sledovány v¹echny akce u¾ivatele a Speech Dispatcher.

Reprodukce chyby se ukonèí stiskem kláves @kbd{C-e C-f}.  Poté, co je
ukonèena, jsou do bufferu, kde byl pøíkaz @code{speechd-bug-reproduce}
vyvolán, vlo¾eny informace o@tie{}reprodukci chyby.

Tento pøíkaz je u¾iteèný v@tie{}pøípadì, kdy chcete poskytnout
informace o@tie{}chybì bez generování nového oznámení o@tie{}chybì.
@end ftable

Kdy¾ oznamujete chyby, mìjte prosím v¾dy na pamìti následující pokyny:

@itemize @bullet
@item
Napi¹te o@tie{}chybì co nejvíce informací.  Popi¹te, co nefunguje,
jaké je vámi oèekávané chování, jaké akce chybu vyvolaly, co je
zvlá¹tního na va¹em Emacsovém prostøedí nebo konfiguraci Speech
Dispatcher, atd.  Nesna¾te se pøíli¹ pøemý¹let nad tím, která
informace je dùle¾itá a která není --- pro vývojáøe mù¾e být dùle¾itá
ka¾dá informace, tak¾e nezapomeòte uvést cokoli, co mù¾e být
potenciálnì dùle¾ité.  Radìji uvádìjte informací více ne¾ ménì.
Chybìjící informace mù¾e znamenat, ¾e vývojáøi nebudou schopni
s@tie{}chybou nic udìlat.

@item
Buïte co nejpøesnìj¹í.  Neoèekávajte, ¾e vývojáøi znají kontext nebo
¾e ví, jakým zpùsobem Emacs a speechd-el pou¾íváte.  Pou¾ívejte pøesné
popisy --- místo pouhého ``kdy¾ zavolám foo'' pi¹te lépe ``kdy¾
stisknu klávesy `M-x foo RET', èím¾ se vyvolá pøíkaz `foo' ''.  Nebo
místo ``neøíká, co by mìlo'' pi¹te ``øíká `bla bla' místo oèekávaného
`ble ble ble', pøièem¾ `ble ble ble' je text celého èteného øádku''.

@item
Kdy¾ reprodukujete chybu, sna¾te se mít zapnuto logování Speech
Dispatcher na co nejvy¹¹í úroveò --- nastavte v@tie{}konfiguraèním
souboru @file{speechd.conf} volbu @code{LogLevel} na hodnotu @code{5}.

@item
Kdy¾ reprodukujete chybu, neprovádìjte ¾ádné nadbyteèné akce a
proveïte @kbd{C-e C-f} hned jak je chyba zreprodukována.  Zabráníte
tak tomu, aby se podstatné informace získané z@tie{}logovacích souborù
utopily v@tie{}nadbyteèném balastu.

@item
Mù¾ete se také podívat na pokyny pro oznamování chyb Speech Dispatcher,
viz @ref{Reporting Bugs,,,speechd,Speech Dispatcher}.
@end itemize

@c ****************************************************************************

@node Elispová knihovna, Kontaktní informace, U¾ivatelská pøíruèka, Top
@chapter Elispová knihovna speechd-el

Momentálnì není ke knihovnì k@tie{}dispozici ¾ádný skuteèný programátorský
manuál.  Podívejte se tedy prosím na dokumentaèní øetìzce dostupných
promìnných, funkcí a maker.

Nicménì se mù¾ete (a@tie{}mìli byste) øídit následujícími radami:

@itemize @bullet
@item
Nepou¾ívejte ¾ádné funkce, promìnné nebo jiné lispové objekty, jejich¾
jména zaèínají prefixem @code{speechd--} nebo @code{speechd-speak--}.
Tyto objekty jsou pova¾ovány za privátní a mohou se kdykoliv bez
upozornìní zmìnit nebo být zru¹eny.

@item
@vindex speechd-client-name
Jestli¾e chcete vybrat nebo vytvoøit konkrétní spojení, udìlejte to
prostøednictvím nastavení hodnoty promìnné @code{speechd-client-name}:

@lisp
(let ((speechd-client-name "nìco"))
  ... kód pou¾ívající spojení "nìco" ... )
@end lisp

Mìjte prosím na pamìti, ¾e obvykle není dobrým nápadem otevøít
souèasnì dvì spojení na Speech Dispatcher se shodným klientským
jménem.

@item
Jinak by na vás nemìly èíhat ¾ádná zvlá¹tní pøekvapení a jakýkoliv
rozumný kód by mìl být bezproblémový.
@end itemize

Mo¾ná vás je¹tì mù¾e zajímat @ref{Pokroèilá konfigurace}.

@c ****************************************************************************

@node Kontaktní informace, Kopírování tohoto manuálu, Elispová knihovna, Top
@chapter Kontaktní informace
@cindex autoøi
@cindex chyby
@cindex kontakty

Pokud chcete oznámit chybu speechd-el, za¹lete nám kompletní informaci
o@tie{}chybì na adresu @email{speechd-el@@bugs.freebsoft.org}.  Pokud
nám chcete poslat záplatu speechd-el, mù¾ete pou¾ít tuté¾ adresu.

@emph{Prosíme}, pøed zasláním oznámení o@tie{}chybì si pøeètìte pokyny
pro oznamování chyb, see @ref{Oznamování chyb}.  Budete-li se dr¾et
uvedenými radami, umo¾níte nám zpracovat va¹e oznámení o@tie{}chybì
efektivnìji a tím pádem s@tie{}lep¹í a rychlej¹í odezvou.

Máte-li jakékoliv otázky, námìty nebo cokoliv dal¹ího, co nám chcete
sdìlit, neváhejte se obrátit na adresu @email{speechd@@freebsoft.org}.

@c ****************************************************************************

@node Kopírování tohoto manuálu, Index, Kontaktní informace, Top
@appendix GNU Free Documentation License

@cindex FDL, GNU Free Documentation License
@center Version 1.2, November 2002

@include fdl.texi

@c ****************************************************************************

@node Index,  , Kopírování tohoto manuálu, Top
@unnumbered Index

@printindex cp

@bye

@c  LocalWords:  chyph def ntprefix cs input comment of header documentlanguage
@c  LocalWords:  documentencoding VERSION el value end copying quotation is and
@c  LocalWords:  Permission granted distribute or modify this document under gc
@c  LocalWords:  the terms Documentation License Version any later version with
@c  LocalWords:  published Foundation Sections Cover Texts Back license section
@c  LocalWords:  included entitled Sound Emacsové Dispatcher title subtitle tie
@c  LocalWords:  author page contents node Elispová elispových chapter emacsový
@c  LocalWords:  itemize bullet Elispovou emacsové emacsových elispovou file
@c  LocalWords:  enumerate example make compile lisp speak nil code table ref
@c  LocalWords:  global toggle speaking subsection read other window word char
@c  LocalWords:  paragraph next previous last message cancel resume key rate
@c  LocalWords:  predefined connection language punctuation all none some icon
@c  LocalWords:  capital character spell voice number pitch output spelling say
@c  LocalWords:  sound repeat faces localhost timeout default notification name
@c  LocalWords:  important progress deleted buffers force self insert command
@c  LocalWords:  insertions one comint align signal empty beginning backward
@c  LocalWords:  properties face lock movement always never voices parameters
@c  LocalWords:  property customize add connections minibuffer area define hook
@c  LocalWords:  elispový feedback before after suspend emacs function garbage
@c  LocalWords:  collection cons threshold elispovým autorepeatu client protect
@c  LocalWords:  appendix November include unnumbered bye
